import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Footer from "@/components/Footer";
import Showcase from "@/components/Showcase";
import Testimonials from "@/components/Testimonials";
import Services from "@/components/Services";
import Introduction from "@/components/Introduction";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Run CMD Create",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen flex flex-col justify-between`}>
        <Navbar />
        <Hero />
        <Introduction />
        <Showcase />
        {children}
        <Services />
        <Testimonials />
        <Footer />
      </body>
    </html>
  );
}
